config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "heat_maps#index"

  # post 'trades_import', to: 'trades#import'
  # get 'new_trades_import', to: 'trades#new_import'
  # resources :trades, only: [:new, :create, :edit, :update]
  resources :heat_maps
  resources :trading_alerts
  # resources :dashboard, only: [:show, :index]
end

app/models/heat_map.rb
require "securerandom"

class HeatMap < ApplicationRecord
    belongs_to :user

    before_create :generate_random_id
    validates :name, presence: true
    validates :tickers, presence: true
    validate :max_ticker_count

    # TODO validate it is alphanumeric?

    private

    def generate_random_id
        self.id = SecureRandom.uuid
    end

    def max_ticker_count
        if tickers.split(',').count > 25
          errors.add(:tickers_count, "can be up to 25")
        end
    end
end

app/controllers/heat_maps_controller.rb
class HeatMapsController < ApplicationController
    def index
        @heat_maps = HeatMap.where user_id: current_user.id
    end

    def new
        @heat_map = HeatMap.new
    end

    def create
        tickers = parse_param_tickers_to_list

        @heat_map = HeatMap.new tickers: tickers.join(','), name: heat_map_params[:name], user_id: current_user.id

        if @heat_map.save
            DailyQuotes.delay.backfill tickers
            redirect_to action: :index
        else
            render :new, heat_map: @heat_map
        end
    end

    def show
        @heat_map = HeatMap.find params["id"]
        @data = HeatMapService.new.get @heat_map
        @name = @heat_map.name
        @periods = ["1d", "1w", "1m", "3m"]
    end

    def edit
        @heat_map = HeatMap.find params["id"]
    end

    def update
        @heat_map = HeatMap.find params["id"]
        @heat_map.name = heat_map_params["name"]

        tickers = parse_param_tickers_to_list
        extra_tickers = tickers - @heat_map.tickers.split(",")

        @heat_map.tickers = tickers.join(",")

        if @heat_map.save
            if !extra_tickers.empty?
                DailyQuotes.delay.backfill extra_tickers
            end

            redirect_to action: :index
        else
            render :edit, heat_map: @heat_map
        end
    end

    def destroy
        @heat_map = HeatMap.find params["id"]
        @heat_map.destroy

        flash.notice = "Heat map '#{@heat_map.name}' was deleted"

        redirect_to action: :index
    end

    private

    def parse_param_tickers_to_list
        heat_map_params['tickers'].
            split(',').
            map(&:strip).
            reject(&:empty?).
            map(&:upcase)
    end

    def heat_map_params
        secure_params = params.require(:heat_map).permit(:tickers, :name)
        secure_params
    end
end

app/views/heat_maps/edit.erb
<h1>Edit Heat Map</h1>

<% if @heat_map.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@heat_map.errors.count, "error") %> prohibited this heat map from being saved:</h2>

    <ul>
      <% @heat_map.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @heat_map do |form| %>
    <div class="form-group">
        <%= form.label :name, class: 'form-label' %><br>
        <%= form.text_field :name, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= form.label :tickers, class: 'form-label' %><br>
        <%= form.text_field :tickers, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= form.submit 'Save', class: 'btn btn-primary btn-lg' %>
    </div>
<% end %>

app/views/heat_maps/index.erb
<div class="heading">
    <h1>
        Heat Maps
    </h1>

    <%= link_to new_heat_map_path, class: 'btn btn-sm btn-success', title: 'Create new', data: {toggle: 'tooltip'} do %>
        <i class="far fa-plus-square"></i>
    <% end %>
</div>

<% if @heat_maps.size == 0 %>
    <span>You don't have any heat maps. <%= link_to 'Create one', new_heat_map_path %> </span>
<% else %>
    <ul class="list-group list-group-flush">
        <% @heat_maps.each do |heat_map| %>
            <li class="list-group-item d-flex justify-content-between align-items-center">
                <% if(((Time.now.utc - heat_map.updated_at) / 1.minute).round < 2) %>
                    <span><%="#{heat_map.name}"%> heatmap was just created or updated. Fetching data for it... Will be available in ~ 2 mins.</span>
                <% else %>
                    <%= link_to "#{heat_map.name}", heat_map_path(heat_map) %>
                    <%= link_to heat_map_path(heat_map), data: { confirm: "Are you sure you want to delete #{heat_map.name}?" }, method: :delete, class: 'text-danger' do %>
                        <i class="fas fa-trash-alt"></i>
                    <% end %>
                <% end %>
            </li>
        <% end %>
    </ul>
<% end %>

app/views/heat_maps/new.erb
<h1>New Heat Map</h1>

<% if @heat_map.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@heat_map.errors.count, "error") %> prohibited this heat map from being saved:</h2>

    <ul>
      <% @heat_map.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @heat_map do |form| %>
  <div class="form-group">
    <%= form.label :name, class: "form-label" %><br>
    <%= form.text_field :name, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :tickers, class: "form-label" %><br>
    <%= form.text_field :tickers, class: 'form-control', placeholder: 'Max 25 comma separated tickers e.g. AMZN,MSFT,AAPL...' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Add', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>

app/views/heat_maps/show.erb
<script type="text/javascript" src="https://s3.tradingview.com/tv.js"></script>

<div class="heatmap-page">
    <div class="heading">
        <h1>
            <%= "#{@name}" %>
        </h1>

        <%= link_to edit_heat_map_path(@heat_map), class: 'btn btn-link' do %>
            <i class="fas fa-edit"></i>
        <% end %>
    </div>

    <div class="heatmap">
        <% @data.each do |ticker, data| %>
            <% if data.nil? %>
                <div
                    class="js-stock symbol"
                    data-symbol=<%="#{ticker}"%>>
                    <div class="ticker-and-percentage">
                        <span>
                            <%="#{ticker}"%>
                        </span>
                        <span>
                            No data
                        </span>
                    </div>
                </div>
            <% else %>
                <div
                    class="js-stock js-stock-with-data symbol"
                    data-symbol=<%="#{ticker}"%>
                    data-performance-1d=<%="#{data['performance']['1d']}"%>>
                    <div class="ticker-and-percentage" data-toggle="tooltip" title=<%="#{number_to_currency data['price']}"%>>
                        <span>
                            <%="#{ticker}"%>
                        </span>
                        <span>
                            <%= number_to_percentage(data['performance']['1d'], precision: 2) %>
                        </span>
                    </div>
                </div>
            <% end %>

        <% end %>
    </div>

    <div class="tradingview-widget-container">
        <div id="technical-analysis"></div>
        <div class="tradingview-widget-copyright">Charts by TradingView</div>
    </div>

    <div class="heatmap-table">
        <table class="table table-sm">
            <thead>
                <tr>
                    <th scope="col"></th>
                    <% @periods.each do |column_text| %>
                        <th scope="col"><%="#{column_text}"%></th>
                    <% end %>
                </tr>
            </thead>
            <tbody>
                <% @data.each do |ticker, data| %>
                    <tr>
                        <td>
                            <%="#{ticker}"%>
                        </td>
                        <% if !data.nil? %>
                            <% data['performance'].keys.each do |key| %>
                                <td class="js-performance-percentages">
                                    <%= number_to_percentage(data['performance'][key], precision: 2) %>
                                </td>
                            <% end %>
                        <% end %>
                    </tr>
                <% end %>
            </tbody>
        </table>
    </div>
</div>

<%= javascript_pack_tag 'show_heat_map' %>