config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "heat_maps#index"

  # post 'trades_import', to: 'trades#import'
  # get 'new_trades_import', to: 'trades#new_import'
  # resources :trades, only: [:new, :create, :edit, :update]
  resources :heat_maps
  resources :trading_alerts
  # resources :dashboard, only: [:show, :index]
end

app/models/trading_alert.rb
class TradingAlert < ApplicationRecord
    belongs_to :user

    validate :valid_rule

    validates :ticker, presence: true
    validates :rule, presence: true

    before_save do
      self.ticker.strip!
      self.ticker.upcase!
    end

    def valid_rule
      # TODO improve
      delimiters = ['>=', '<=', '<', '>']
      rule_parts = rule.split(Regexp.union(delimiters)).map { |token| token.strip }
      if rule_parts.size != 2 || rule_parts[0].upcase != "PRICE" || !is_number?(rule_parts[1])
        errors.add(:rule, "invalid format. Should be 'price >= 42.42'")
      end
    end

    def is_number? string
      true if Float(string) rescue false
    end
end

app/controllers/trading_alerts_controller.rb
class TradingAlertsController < ApplicationController
    def index
        @active_trading_alerts = TradingAlert.where user_id: current_user.id, triggered: false
        @recently_triggered_trading_alerts = TradingAlert.where user_id: current_user.id, triggered: true, triggered_on: (10.days.ago..Time.now)
    end

    def new
        @trading_alert = TradingAlert.new
    end

    def create
        @trading_alert = TradingAlert.new trading_alert_params.merge(user_id: current_user.id)

        if @trading_alert.save
            DailyQuotes.delay.backfill [trading_alert_params['ticker'].upcase]
            redirect_to action: :index
        else
            render :new, trading_alert: @trading_alert
        end
    end

    def destroy
        @trading_alert = TradingAlert.find params["id"]
        @trading_alert.destroy

        flash.notice = "Trading alert '#{@trading_alert.ticker} - #{@trading_alert.rule}' was deleted"

        redirect_to action: :index
    end

    private

    def trading_alert_params
        secure_params = params.require(:trading_alert).permit(:ticker, :rule)
        secure_params[:rule] = secure_params[:rule].strip if secure_params[:rule]
        secure_params[:ticker] = secure_params[:ticker].strip.upcase if secure_params[:ticker]
        secure_params
    end
end

app/views/trading_alerts/index.erb
<h1>Trading Alerts</h1>

<% if @active_trading_alerts.size == 0 %>
    <span>You don't have any active price alerts. <%= link_to 'Create one', new_trading_alert_path %> </span>
<% else %>
    <h2>Active trading alerts</h2>

    <table class="table table-sm table-hover">
        <thead>
        <tr>
            <th scope="col">Ticker</th>
            <th scope="col">Rule</th>
            <th scope="col">Created On</th>
            <th scope="col"></th>
        </tr>
        </thead>
        <tbody>
            <% @active_trading_alerts.each do |trading_alert| %>
                <tr>
                    <td>
                        <%= trading_alert.ticker %>
                    </td>
                    <td>
                        <%= trading_alert.rule %>
                    </td>
                    <td>
                        <%= trading_alert.created_at.strftime('%F') %>
                    </td>
                    <td>
                        <%= link_to "Delete", trading_alert_path(trading_alert), data: { confirm: "Are you sure you want to delete #{trading_alert.ticker} - #{trading_alert.rule}?" }, method: :delete %>
                    </td>
                </tr>
            <% end %>
        </tbody>
    </table>

    <%= link_to 'Add trading alert', new_trading_alert_path %>
<% end %>


<% if @recently_triggered_trading_alerts.size > 0 %>
    <h2>Recently triggered trading alerts</h2>

    <table class="table table-sm table-hover">
        <thead>
        <tr>
            <th scope="col">Ticker</th>
            <th scope="col">Rule</th>
            <th scope="col">Triggered on</th>
            <th scope="col">Price</th>
        </tr>
        </thead>
        <tbody>
            <% @recently_triggered_trading_alerts.each do |trading_alert| %>
                <tr>
                    <td>
                        <%= trading_alert.ticker %>
                    </td>
                    <td>
                        <%= trading_alert.rule %>
                    </td>
                    <td>
                        <%= trading_alert.triggered_on.strftime('%c') %>
                    </td>
                    <td>
                        <%= number_to_currency trading_alert.price%>
                    </rd>
                </tr>
            <% end %>
        </tbody>
    </table>
<% end %>

app/views/trading_alerts/new.erb
<h1>New Trading Alert</h1>

<% if @trading_alert.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@trading_alert.errors.count, "error") %> prohibited this trading alert from being saved:</h2>

    <ul>
      <% @trading_alert.errors.each do |error| %>
        <li><%= error.full_message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= form_with model: @trading_alert do |form| %>
  <div class="form-group">
    <%= form.label :ticker, class: 'form-label' %><br>
    <%= form.text_field :ticker, step: :any, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :rule, class: 'form-label' %><br>
    <%= form.text_field :rule, class: 'form-control', value: 'price >= 100', placeholder: 'ie price > 100.20' %>
  </div>

  <div class="form-group">
    <%= form.submit 'Add', class: 'btn btn-primary btn-lg' %>
  </div>
<% end %>