config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "heat_maps#index"

  # post 'trades_import', to: 'trades#import'
  # get 'new_trades_import', to: 'trades#new_import'
  # resources :trades, only: [:new, :create, :edit, :update]
  resources :heat_maps
  resources :trading_alerts
  # resources :dashboard, only: [:show, :index]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TradingJournal</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload'  %>
  </head>

  <body class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <%= link_to 'Trading Journal', root_path, class: 'navbar-brand' %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to "Heat Maps", heat_maps_path, class: 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to "Alerts", trading_alerts_path, class: 'nav-link'  %>
        </li>
        <li class="nav-item">
          <%= link_to "Logout", destroy_user_session_path, method: :delete, class: 'nav-link'  %>
        </li>
      </ul>
    </div>
  </nav>
    <div class="notice" role="alert">
      <%= notice %>
    </div>
    <div class="alert" role="alert">
      <%= alert %>
    </div>
    <%= yield %>
  </body>
</html>